services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project/backend:/src/project/backend:cached
    working_dir: /src/project/backend
    ports:
      - "5000:8080"

