services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./project/backend:/src/project/backend
    working_dir: /src/project/backend
    ports:
      - "5000:8080"

