services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project/backend:/src/project/backend
    working_dir: /src/project/backend
    command: dotnet watch run --urls http://0.0.0.0:8080
    ports:
      - "5000:8080"

